### ISSUE TITLE
Setup 

### ISSUE THREAD

**Issue by ShekerZoiD** [XKMR/discord-link-phishing#7]
Hello i need some help setting this up i can guarrentee i am using this for security purposes leave your discord as a reply i will make sure to contact you

**Comment by XKMR** [comment]
Hi, sorry for the delay (there is a internet shortage here)
Setting this up does require a basic html and php knowledge but I will try my best to help you get through it.

So what exactly this codr is supposed to be and where should it be located:
This is a code designed for a web server of some kind.
It means that it should be hosted on a website accessible by the victim.
There are a couple of free website hosting platforms (you can search for them in google) but the one I personally use and recommend is: https://www.000webhost.com/
It is free but they might take your website down after a while so you will need some alt accounts. 
After you have created an account and have access to the web server files, you should download the code from github and copy everything that is in the downloaded zip file and paste it to the website. 
Now you have completed the setup.
This should be the final phishing address (with your own website name): www.yourdomain.com/gift/HJ9fh9hGfgfijh93
Also make sure to carefully read the [Readme.md](https://github.com/XKMR/discord-link-phishing/blob/main/README.md) file because I have left some important details on there.

**Comment by Decrypt1231** [comment]
> Hi, sorry for the delay (there is a internet shortage here) Setting this up does require a basic html and php knowledge but I will try my best to help you get through it.
> 
> So what exactly this code is supposed to be and where should it be located: This is a code designed for a web server of some kind. It means that it should be hosted on a website accessible by the victim. There are a couple of free website hosting platforms (you can search for them in google) but the one I personally use and recommend is: https://www.000webhost.com/ It is free but they might take your website down after a while so you will need some alt accounts. After you have created an account and have access to the web server files, you should download the code from github and copy everything that is in the downloaded zip file and paste it to the website. Now you have completed the setup. This should be the final phishing address (with your own website name): [www.yourdomain.com/gift/HJ9fh9hGfgfijh93](http://www.yourdomain.com/gift/HJ9fh9hGfgfijh93) Also make sure to carefully read the [Readme.md](https://github.com/XKMR/discord-link-phishing/blob/main/README.md) file because I have left some important details on there.

How do i move the files from the zip link to my website HTML ?

**Comment by XKMR** [comment]
depends on the hosting service, but you need to access some sort of file system

**Comment by navos8** [comment]
Sorry but where do we exactly paste the files ?

**Comment by XKMR** [comment]
detailed setup guide available in readme.md
